server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;
  location / { try_files $uri $uri/ /index.html; }
  location = /api/standings/esp.1 {
    proxy_ssl_server_name on;
    proxy_pass https://site.api.espn.com/apis/v2/sports/soccer/esp.1/standings;
  }
  location ~ ^/api/(esp\\.1|eng\\.1|ita\\.1|uefa\\.champions)/(.*)$ {
    proxy_ssl_server_name on;
    rewrite ^/api/(esp\\.1|eng\\.1|ita\\.1|uefa\\.champions)/(.*)$ /apis/site/v2/sports/soccer/$1/$2 break;
    proxy_pass https://site.api.espn.com;
  }
  location = /health {
    default_type application/json;
    return 200 '{"ok":true}';
  }
}
