const LEAGUES={LaLiga:'esp.1',Champions:'uefa.champions',Premier:'eng.1',SerieA:'ita.1'};
const teamConfigs={barca:{name:'FC Barcelona',league:'esp.1',id:'83'},madrid:{name:'Real Madrid',league:'esp.1',id:'86'},city:{name:'Manchester City',league:'eng.1',id:'382'}};
const state={matches:[],filter:'Tots'};
const crest=t=>`<span class="mini-crest">${(t||'?').trim()[0]||'?'}</span>`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path){const r=await fetch(`/api/${path}`,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`API ${r.status}`);return r.json()}
function eventToMatch(e,league){const c=e.competitions?.[0];const comps=c?.competitors||[];const home=comps.find(x=>x.homeAway==='home')||comps[0];const away=comps.find(x=>x.homeAway==='away')||comps[1];const stateName=c?.status?.type?.name||e.status?.type?.name||'';const live=['STATUS_IN_PROGRESS','STATUS_HALFTIME','STATUS_END_PERIOD'].includes(stateName);const completed=['STATUS_FINAL','STATUS_FULL_TIME','STATUS_FINAL_OT','STATUS_FINAL_PEN'].includes(stateName);return{league,time:e.date?new Date(e.date).toLocaleTimeString('ca-ES',{hour:'2-digit',minute:'2-digit'}):'',home:home?.team?.displayName||'Local',away:away?.team?.displayName||'Visitant',hs:home?.score??'—',as:away?.score??'—',live,completed,clock:c?.status?.displayClock||'',id:e.id};}
async function loadMatches(){const results=await Promise.all(Object.entries(LEAGUES).map(async([name,slug])=>{try{const data=await api(`scoreboard?sport=soccer&league=${slug}`);return(data.events||[]).map(e=>eventToMatch(e,name));}catch{return[]}}));state.matches=results.flat().sort((a,b)=>Number(b.live)-Number(a.live)||a.time.localeCompare(b.time));renderMatches();updateHero();document.querySelector('#matchesStatus').textContent=`${state.matches.length} partits carregats · actualització automàtica cada 30 segons`}
function renderMatches(){const data=state.filter==='Tots'?state.matches:state.matches.filter(m=>m.league===state.filter);const el=document.querySelector('#matches');el.innerHTML=data.length?data.map(m=>`<article class="match"><div class="meta"><span>${esc(m.league)}</span><span>${m.live?'<span class="status">● EN DIRECTE '+esc(m.clock)+'</span>':m.completed?'FINAL':esc(m.time)}</span></div><div class="teams"><div class="team"><span class="team-left">${crest(m.home)}${esc(m.home)}</span><span class="score">${esc(m.hs)}</span></div><div class="team"><span class="team-left">${crest(m.away)}${esc(m.away)}</span><span class="score">${esc(m.as)}</span></div></div></article>`).join(''):'<div class="empty">No hi ha partits per aquest filtre avui.</div>'}
function updateHero(){const live=state.matches.find(m=>m.live)||state.matches.find(m=>m.league==='LaLiga');const hero=document.querySelector('#heroScore');if(!live){hero.innerHTML='<div><span class="crest blue">⚽</span><strong>Sense partit</strong></div><div class="big-score"><b>—</b><em>—</em><b>—</b></div><div><span class="crest red">⚽</span><strong>en directe</strong></div>';document.querySelector('#heroMinute').textContent='Esperant el proper partit';return}hero.innerHTML=`<div><span class="crest blue">⚽</span><strong>${esc(live.home)}</strong></div><div class="big-score"><b>${esc(live.hs)}</b><em>—</em><b>${esc(live.as)}</b></div><div><span class="crest red">⚽</span><strong>${esc(live.away)}</strong></div>`;document.querySelector('#heroMinute').innerHTML=live.live?`<span class="live-pill">● LIVE</span> ${esc(live.clock)}`:live.completed?'FINAL':esc(live.time);document.querySelector('#liveLabel').textContent=live.live?'EN DIRECTE':'PROPER PARTIT'}
async function loadStandings(){const body=document.querySelector('#standings');try{const data=await api('standings?sport=soccer&league=esp.1');const entries=data.children?.flatMap(g=>g.standings?.entries||[])||data.standings?.entries||[];const rows=entries.slice(0,20).map((e,i)=>{const team=e.team||{};const stats=Object.fromEntries((e.stats||[]).map(s=>[s.name,s.value??s.displayValue]));return`<tr><td class="rank">${i+1}</td><td><span class="club">${crest(team.displayName)}${esc(team.displayName)}</span></td><td>${stats.gamesPlayed??stats.gp??'—'}</td><td>${stats.goalDifference??stats.difference??'—'}</td><td><b>${stats.points??'—'}</b></td></tr>`});body.innerHTML=rows.length?rows.join(''):'<tr><td colspan="5">No s’ha pogut carregar la classificació.</td></tr>'}catch{body.innerHTML='<tr><td colspan="5">No s’ha pogut carregar la classificació ara mateix.</td></tr>'}}
async function loadNews(){const el=document.querySelector('#news');try{const data=await api('news?sport=soccer&league=esp.1');const items=(data.articles||[]).slice(0,4);el.innerHTML=items.length?items.map(a=>`<article class="news"><span class="news-icon">📰</span><div><small>${a.published?new Date(a.published).toLocaleString('ca-ES'):''}</small><h3><a href="${esc(a.links?.web?.href||'#')}" target="_blank" rel="noopener">${esc(a.headline||a.description||'Notícia')}</a></h3></div></article>`).join(''):'<div class="empty">No hi ha notícies disponibles.</div>'}catch{el.innerHTML='<div class="empty">No s’han pogut carregar les notícies.</div>'}}
async function loadTransfers(){const el=document.querySelector('#transfers');try{const leagues=['esp.1','eng.1','ita.1'];const all=(await Promise.all(leagues.map(async league=>{try{const d=await api(`transactions?sport=soccer&league=${league}`);return d.transactions||[]}catch{return []}}))).flat();const items=all.slice(0,9);el.innerHTML=items.length?items.map(t=>{const name=t.athlete?.displayName||t.player?.displayName||'Jugador';const detail=t.description||t.type?.text||t.team?.displayName||'Moviment de plantilla';return`<article class="transfer"><span class="avatar">${esc(name.split(' ').map(x=>x[0]).join('').slice(0,3))}</span><div><h3>${esc(name)}</h3><p>${esc(detail)}</p></div><span class="arrow">→</span></article>`}).join(''):'<div class="empty">La font actual no publica moviments de fitxatges de futbol.</div>';document.querySelector('#transfersStatus').textContent=items.length?'Moviments recents carregats des de la font de dades.':'No hi ha moviments disponibles ara mateix.'}catch{el.innerHTML='<div class="empty">No s’han pogut carregar els fitxatges.</div>';document.querySelector('#transfersStatus').textContent='Error carregant moviments.'}}
function positions(i){const p=[['GK',50,88],['DF',18,68],['DF',38,76],['DF',62,76],['DF',82,68],['MF',28,50],['MF',50,58],['MF',72,50],['FW',25,27],['FW',50,18],['FW',75,27]];return p[i]}
async function loadTeam(key){const cfg=teamConfigs[key];document.querySelector('#lineupName').textContent=cfg.name;document.querySelector('#lineupMeta').textContent='Carregant plantilla...';try{const data=await api(`roster?sport=soccer&league=${cfg.league}&team=${cfg.id}`);const athletes=data.athletes||data.athletes?.items||[];const players=athletes.map(x=>x.athlete||x).filter(Boolean).slice(0,25);const starters=players.slice(0,11);document.querySelector('#pitch').innerHTML=starters.map((p,i)=>{const pos=positions(i);return`<div class="player" style="left:${pos[1]}%;top:${pos[2]}%"><i>${esc((p.displayName||p.fullName||'?')[0])}</i>${esc(p.displayName||p.fullName||'Jugador')}</div>`}).join('');document.querySelector('#benchPlayers').textContent=players.slice(11).map(p=>p.displayName||p.fullName||'Jugador').join(' · ')||'Sense dades';document.querySelector('#lineupMeta').textContent=`Plantilla actual · ${players.length} jugadors mostrats`}catch{document.querySelector('#pitch').innerHTML='<div class="empty">No s’ha pogut carregar la plantilla.</div>';document.querySelector('#benchPlayers').textContent='Torna-ho a provar més tard';document.querySelector('#lineupMeta').textContent='Font de dades no disponible'}}
function tick(){document.querySelector('#clock').textContent=new Date().toLocaleTimeString('ca-ES',{hour12:false})}
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.filter=b.dataset.filter;renderMatches()}));
document.querySelector('#teamSelect').addEventListener('change',e=>loadTeam(e.target.value));
document.querySelector('#showAllTransfers').addEventListener('click',loadTransfers);
document.querySelector('#menuBtn').addEventListener('click',()=>{const nav=document.querySelector('.nav');nav.style.display=nav.style.display==='flex'?'none':'flex';nav.style.position='absolute';nav.style.top='72px';nav.style.left='0';nav.style.right='0';nav.style.padding='15px 22px';nav.style.background='#07111f';nav.style.flexDirection='column'});
document.querySelector('#year').textContent=new Date().getFullYear();tick();setInterval(tick,1000);
async function refresh(){await Promise.allSettled([loadMatches(),loadStandings(),loadNews(),loadTransfers()])}
refresh();loadTeam('barca');setInterval(loadMatches,30000);setInterval(loadStandings,300000);