const LEAGUES={LaLiga:'esp.1',Champions:'uefa.champions',Premier:'eng.1',SerieA:'ita.1'};
const teamConfigs={barca:{name:'FC Barcelona',league:'esp.1',id:'83'},madrid:{name:'Real Madrid',league:'esp.1',id:'86'},city:{name:'Manchester City',league:'eng.1',id:'382'}};
const state={matches:[],filter:'Tots'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=u=>{try{const x=new URL(u,location.origin);return ['http:','https:'].includes(x.protocol)?x.href:'#'}catch{return '#'}};
function crest(name,logo,large=false){return logo?`<img class="${large?'crest-img big':'crest-img'}" src="${esc(logo)}" alt="" loading="lazy">`:`<span class="mini-crest" aria-hidden="true">${esc((name||'?').trim()[0]||'?')}</span>`}
async function api(path,timeout=10000){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeout);try{const r=await fetch(`/api/${path}`,{headers:{Accept:'application/json'},signal:controller.signal,cache:'no-store'});if(!r.ok)throw new Error(`API ${r.status}`);return await r.json()}finally{clearTimeout(timer)}}
function retryButton(action){return `<button class="btn small ghost retry-btn" type="button" data-retry="${esc(action)}">Torna-ho a intentar</button>`}
function bindRetries(){document.querySelectorAll('[data-retry]').forEach(b=>b.addEventListener('click',()=>{const action=b.dataset.retry;if(action==='matches')loadMatches();if(action==='standings')loadStandings();if(action==='news')loadNews();if(action==='transfers')loadTransfers();if(action==='team')loadTeam(document.querySelector('#teamSelect').value)}))}
function eventToMatch(e,league){const c=e.competitions?.[0];const comps=c?.competitors||[];const home=comps.find(x=>x.homeAway==='home')||comps[0];const away=comps.find(x=>x.homeAway==='away')||comps[1];const status=c?.status?.type||e.status?.type||{};return{league,time:e.date?new Date(e.date).toLocaleTimeString('ca-ES',{hour:'2-digit',minute:'2-digit'}):'',date:e.date,home:home?.team?.displayName||'Local',away:away?.team?.displayName||'Visitant',homeLogo:home?.team?.logo||home?.team?.logos?.[0]?.href,awayLogo:away?.team?.logo||away?.team?.logos?.[0]?.href,hs:home?.score??'—',as:away?.score??'—',live:status.state==='in'||['STATUS_IN_PROGRESS','STATUS_HALFTIME','STATUS_END_PERIOD'].includes(status.name),completed:Boolean(status.completed)||['STATUS_FINAL','STATUS_FULL_TIME','STATUS_FINAL_OT','STATUS_FINAL_PEN'].includes(status.name),clock=status.displayClock||'',id:e.id,summaryLeague:LEAGUES[league]||'esp.1'};}
async function loadMatches(){const statusEl=document.querySelector('#matchesStatus');statusEl.innerHTML='Actualitzant resultats...';let failed=0;const results=await Promise.all(Object.entries(LEAGUES).map(async([name,slug])=>{try{const data=await api(`${slug}/scoreboard`);return(data.events||[]).map(e=>eventToMatch(e,name))}catch{failed++;return[]}}));state.matches=results.flat().sort((a,b)=>Number(b.live)-Number(a.live)||(a.date||'').localeCompare(b.date||''));renderMatches();updateHero();statusEl.innerHTML=state.matches.length?`${state.matches.length} partits carregats · actualització automàtica cada 30 segons`:failed===Object.keys(LEAGUES).length?`No s'han pogut carregar les dades. ${retryButton('matches')}`:'No hi ha partits disponibles ara mateix.';bindRetries()}
function renderMatches(){const data=state.filter==='Tots'?state.matches:state.matches.filter(m=>m.league===state.filter);const el=document.querySelector('#matches');el.innerHTML=data.length?data.map(m=>`<article class="match match-clickable" tabindex="0" role="button" data-match-id="${esc(m.id)}" data-league="${esc(m.summaryLeague)}"><div class="meta"><span>${esc(m.league)}</span><span>${m.live?'<span class="status">● EN DIRECTE '+esc(m.clock)+'</span>':m.completed?'FINAL':esc(m.time)}</span></div><div class="teams"><div class="team"><span class="team-left">${crest(m.home,m.homeLogo)}${esc(m.home)}</span><span class="score">${esc(m.hs)}</span></div><div class="team"><span class="team-left">${crest(m.away,m.awayLogo)}${esc(m.away)}</span><span class="score">${esc(m.as)}</span></div></div><div class="match-more">Veure detall →</div></article>`).join(''):'<div class="empty">No hi ha partits per aquest filtre avui.</div>';el.querySelectorAll('.match-clickable').forEach(card=>{const open=()=>openMatch(card.dataset.matchId,card.dataset.league);card.addEventListener('click',open);card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}})})}
function updateHero(){const live=state.matches.find(m=>m.live)||state.matches.find(m=>m.league==='LaLiga');const hero=document.querySelector('#heroScore');if(!live){hero.innerHTML='<div><span class="crest blue">⚽</span><strong>Sense partit</strong></div><div class="big-score"><b>—</b><em>—</em><b>—</b></div><div><span class="crest red">⚽</span><strong>Sense dades en directe</strong></div>';document.querySelector('#heroMinute').textContent='Esperant el proper partit';document.querySelector('#liveLabel').textContent='FUTBOL';return}hero.innerHTML=`<div>${crest(live.home,live.homeLogo)}<strong>${esc(live.home)}</strong></div><div class="big-score"><b>${esc(live.hs)}</b><em>—</em><b>${esc(live.as)}</b></div><div>${crest(live.away,live.awayLogo)}<strong>${esc(live.away)}</strong></div>`;document.querySelector('#heroMinute').innerHTML=live.live?`<span class="live-pill">● LIVE</span> ${esc(live.clock)}`:live.completed?'FINAL':esc(live.time);document.querySelector('#liveLabel').textContent=live.live?'EN DIRECTE':'PROPER PARTIT'}
async function loadStandings(){const body=document.querySelector('#standings');try{const data=await api('standings/esp.1');const entries=data.children?.flatMap(g=>g.standings?.entries||[])||data.standings?.entries||[];const rows=entries.slice(0,20).map((e,i)=>{const team=e.team||{};const stats=Object.fromEntries((e.stats||[]).map(s=>[s.name,s.value??s.displayValue]));return`<tr><td class="rank">${i+1}</td><td><span class="club">${crest(team.displayName,team.logos?.[0]?.href)}${esc(team.displayName)}</span></td><td>${stats.gamesPlayed??stats.gp??'—'}</td><td>${stats.goalDifference??stats.difference??'—'}</td><td><b>${stats.points??'—'}</b></td></tr>`});body.innerHTML=rows.length?rows.join(''):`<tr><td colspan="5">No s’ha pogut carregar la classificació. ${retryButton('standings')}</td></tr>`}catch{body.innerHTML=`<tr><td colspan="5">Error carregant la classificació. ${retryButton('standings')}</td></tr>`}bindRetries()}
async function loadNews(){const el=document.querySelector('#news');try{const data=await api('esp.1/news');const items=(data.articles||[]).slice(0,4);el.innerHTML=items.length?items.map(a=>{const url=safeUrl(a.links?.web?.href);return`<article class="news"><span class="news-icon">📰</span><div><small>${a.published?new Date(a.published).toLocaleString('ca-ES'):''}</small><h3>${url==='#'?esc(a.headline||a.description||'Notícia'):`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(a.headline||a.description||'Notícia')}</a>`}</h3></div></article>`}).join(''):`<div class="empty">No hi ha notícies disponibles. ${retryButton('news')}</div>`}catch{el.innerHTML=`<div class="empty">No s’han pogut carregar les notícies. ${retryButton('news')}</div>`}bindRetries()}
async function loadTransfers(){const el=document.querySelector('#transfers');try{const leagues=['esp.1','eng.1','ita.1'];const all=(await Promise.all(leagues.map(async league=>{try{const d=await api(`${league}/transactions`);return d.transactions||[]}catch{return []}}))).flat();const items=all.slice(0,9);el.innerHTML=items.length?items.map(t=>{const name=t.athlete?.displayName||t.player?.displayName||'Jugador';const detail=t.description||t.type?.text||t.team?.displayName||'Moviment de plantilla';return`<article class="transfer"><span class="avatar">${esc(name.split(' ').map(x=>x[0]).join('').slice(0,3))}</span><div><h3>${esc(name)}</h3><p>${esc(detail)}</p></div><span class="arrow">→</span></article>`}).join(''):`<div class="empty">La font pública actual no proporciona fitxatges de futbol de manera fiable; no inventem dades. ${retryButton('transfers')}</div>`;document.querySelector('#transfersStatus').textContent=items.length?'Moviments recents carregats des de la font de dades.':'No hi ha moviments verificables disponibles ara mateix.'}catch{el.innerHTML=`<div class="empty">No s’han pogut carregar els fitxatges. ${retryButton('transfers')}</div>`;document.querySelector('#transfersStatus').textContent='Error carregant moviments.'}bindRetries()}
function positions(i){const p=[['GK',50,88],['DF',18,68],['DF',38,76],['DF',62,76],['DF',82,68],['MF',28,50],['MF',50,58],['MF',72,50],['FW',25,27],['FW',50,18],['FW',75,27]];return p[i]}
async function loadTeam(key){const cfg=teamConfigs[key];document.querySelector('#lineupName').textContent=cfg.name;document.querySelector('#lineupMeta').textContent='Carregant plantilla...';try{const data=await api(`${cfg.league}/teams/${cfg.id}/roster`);const players=(data.athletes||[]).map(x=>x.athlete||x).filter(Boolean).slice(0,40);document.querySelector('#pitch').innerHTML=players.slice(0,11).map((p,i)=>{const pos=positions(i);return`<div class="player" style="left:${pos[1]}%;top:${pos[2]}%"><i>${esc((p.displayName||p.fullName||'?')[0])}</i>${esc(p.displayName||p.fullName||'Jugador')}</div>`}).join('')||'<div class="empty">Sense jugadors disponibles.</div>';document.querySelector('#benchPlayers').textContent=players.map(p=>p.displayName||p.fullName||'Jugador').join(' · ')||'Sense dades';document.querySelector('#lineupMeta').textContent=`Plantilla actual · ${players.length} jugadors mostrats`}catch{document.querySelector('#pitch').innerHTML=`<div class="empty">No s’ha pogut carregar la plantilla. ${retryButton('team')}</div>`;document.querySelector('#benchPlayers').textContent='No hi ha dades disponibles';document.querySelector('#lineupMeta').textContent='Font de dades no disponible'}bindRetries()}
function extractLineups(data){const rosters=data.rosters||data.lineups||[];return rosters.map(r=>{const team=r.team||{};const players=r.roster||r.players||r.athletes||[];return{name:team.displayName||team.name||'Equip',logo:team.logo||team.logos?.[0]?.href,formation:r.formation?.displayName||r.formation||'',players:players.map(x=>x.athlete||x.player||x).filter(Boolean)}}).filter(x=>x.players.length)}
async function openMatch(id,league){const modal=document.querySelector('#matchModal');const m=state.matches.find(x=>x.id===id);if(!m)return;modal.hidden=false;modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');document.querySelector('#modalTitle').textContent=`${m.home} — ${m.away}`;document.querySelector('#modalScore').textContent=`${m.hs} — ${m.as}`;document.querySelector('#modalContent').innerHTML='<p>Carregant dades del partit...</p>';try{const data=await api(`${league}/summary?event=${encodeURIComponent(id)}`);const lineups=extractLineups(data);if(!lineups.length){document.querySelector('#modalContent').innerHTML='<div class="empty">Aquest partit no té alineacions publicades per la font de dades.</div>';return}document.querySelector('#modalContent').innerHTML=lineups.map(team=>`<div class="lineup-detail"><h3>${crest(team.name,team.logo)}${esc(team.name)} ${team.formation?`<small>${esc(team.formation)}</small>`:''}</h3><div class="players-list">${team.players.map(p=>`<span>${esc(p.displayName||p.fullName||p.name||'Jugador')}</span>`).join('')}</div></div>`).join('')}catch{document.querySelector('#modalContent').innerHTML='<div class="empty">No s’han pogut carregar les dades d’aquest partit ara mateix.</div>'}}
function closeModal(){const modal=document.querySelector('#matchModal');modal.hidden=true;modal.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open')}
function tick(){document.querySelector('#clock').textContent=new Date().toLocaleTimeString('ca-ES',{hour12:false})}
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.filter=b.dataset.filter;renderMatches()}));
document.querySelector('#teamSelect').addEventListener('change',e=>loadTeam(e.target.value));
document.querySelector('#showAllTransfers').addEventListener('click',loadTransfers);
document.querySelector('#closeModal').addEventListener('click',closeModal);document.querySelector('[data-close-modal]').addEventListener('click',closeModal);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
const menuBtn=document.querySelector('#menuBtn'),nav=document.querySelector('#mainNav');menuBtn.addEventListener('click',()=>{const open=nav.classList.toggle('mobile-open');menuBtn.setAttribute('aria-expanded',String(open));menuBtn.setAttribute('aria-label',open?'Tancar menú':'Obrir menú')});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('mobile-open');menuBtn.setAttribute('aria-expanded','false')}));
document.querySelector('#year').textContent=new Date().getFullYear();tick();setInterval(tick,1000);
async function refresh(){await Promise.allSettled([loadMatches(),loadStandings(),loadNews(),loadTransfers()])}
refresh();loadTeam('barca');setInterval(loadMatches,30000);setInterval(loadStandings,300000);